import Italic from './lib/Italic';
import Bold from './lib/Bold';
import Undo from './lib/Undo';
import Redo from './lib/Redo';
import Brush from './lib/Brush';
import Star from './lib/Star';
import Back from './lib/Back';
import File from './lib/File';
import Title from './lib/Title';
import Underline from './lib/Underline';
import Strikethrough from './lib/Strikethrough';
import Ol from './lib/Ol';
import Ul from './lib/Ul';
import Checkbox from './lib/Checkbox';
import Font from './lib/Font';
import Insert from './lib/Insert';
import Image from './lib/Image';
import Link from './lib/Link';
import Code from './lib/Code';
import SplitLine from './lib/SplitLine';
import Paperclip from './lib/Paperclip';
import Table from './lib/Table';
import Indent from './lib/Indent';
import Outdent from './lib/Outdent';
import Align from './lib/Align';
import Aligncenter from './lib/Aligncenter';
import Alignjustify from './lib/Alignjustify';
import Alignleft from './lib/Alignleft';
import Alignright from './lib/Alignright';

exports.Italic = Italic;
exports.Bold = Bold;
exports.Undo = Undo;
exports.Redo = Redo;
exports.Brush = Brush;
exports.Star = Star;
exports.Back = Back;
exports.File = File;
exports.Title = Title;
exports.Underline = Underline;
exports.Strikethrough = Strikethrough;
exports.Ol = Ol;
exports.Ul = Ul;
exports.Checkbox = Checkbox;
exports.Font = Font;
exports.Insert = Insert;
exports.Image = Image;
exports.Link = Link;
exports.Code = Code;
exports.SplitLine = SplitLine;
exports.Paperclip = Paperclip;
exports.Table = Table;
exports.Indent = Indent;
exports.Outdent = Outdent;
exports.Align = Align;
exports.Aligncenter = Aligncenter;
exports.Alignjustify = Alignjustify;
exports.Alignleft = Alignleft;
exports.Alignright = Alignright;